name: CI

on:
  push:
    branches: [ "release-v1" ] # Replace "main" with your branch name
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      # Install Node.js and dependencies
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14.x' # Replace with your desired Node.js version

      # Install project dependencies
      - name: Install dependencies
        run: npm ci

      # Build the project
      - name: Build
        run: npm run build

      # Run tests (if applicable)
      - name: Test
        run: npm test
